### ISSUE TITLE
Cylindrical coordinates python example doesn't work (AttributeError: swigobj)

### ISSUE THREAD

**Issue by keithbriggs** [stevengj/meep#174]
Running the example at https://meep.readthedocs.io/en/latest/Python_Tutorials/Ring_Resonator_in_Cylindrical_Coordinates/ on an Ubuntu 16 system, I get:

> python try_meep_cylindrical_00.py -m 3
-----------
Initializing structure...
time for set_epsilon = 0.00365019 s
Working in Cylindrical dimensions.
Computational cell is 8 x 0 x 0.1 with resolution 10
     block, center = (1,0,0)
          size (1,1e+20,1e+20)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (11.56,11.56,11.56)
time for set_epsilon = 0.000378132 s
-----------
Meep: using complex fields.
harminv0:, frequency, imag., freq., Q, |amp|, amplitude, error
harminv0:, 0.156024731047, -0.000953615951856, 81.8069007463, 1.03166643891, -0.379896671667-0.959173686061i, 1.76071437901e-11+0.0i
run 0 finished at t = 300.0 (6000 timesteps)
Traceback (most recent call last):
  File "try_meep_cylindrical_00.py", line 43, in <module>
    main(args)
  File "try_meep_cylindrical_00.py", line 35, in main
    mp.to_appended("ez", mp.at_every(1 / fcen / 20, mp.output_efield_z))), until=1 / fcen)
  File "/usr/local/lib/python2.7/dist-packages/meep/simulation.py", line 897, in run
    self._run_until(until, step_funcs)
  File "/usr/local/lib/python2.7/dist-packages/meep/simulation.py", line 473, in _run_until
    _eval_step_func(self, func, 'step')
  File "/usr/local/lib/python2.7/dist-packages/meep/simulation.py", line 969, in _eval_step_func
    func(sim, todo)
  File "/usr/local/lib/python2.7/dist-packages/meep/simulation.py", line 1086, in _in_volume
    _eval_step_func(sim, func, todo)
  File "/usr/local/lib/python2.7/dist-packages/meep/simulation.py", line 969, in _eval_step_func
    func(sim, todo)
  File "/usr/local/lib/python2.7/dist-packages/meep/simulation.py", line 1012, in _beg
    _eval_step_func(sim, f, todo)
  File "/usr/local/lib/python2.7/dist-packages/meep/simulation.py", line 967, in _eval_step_func
    func(sim)
  File "/usr/local/lib/python2.7/dist-packages/meep/simulation.py", line 1255, in output_epsilon
    sim.output_component(mp.Dielectric)
  File "/usr/local/lib/python2.7/dist-packages/meep/simulation.py", line 753, in output_component
    vol = self.fields.total_volume() if self.output_volume is None else self.output_volume.swigobj
  File "/usr/local/lib/python2.7/dist-packages/meep/__init__.py", line 415, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, volume, name)
  File "/usr/local/lib/python2.7/dist-packages/meep/__init__.py", line 57, in _swig_getattr
    raise AttributeError(name)
AttributeError: swigobj

Field time usage:
    connnecting chunks: 0.0024209 s
         time stepping: 0.251002 s
         communicating: 0.0456026 s
    Fourier transforming: 0.0038991 s
       everything else: 0.0620632 s

**Comment by ChristopherHogan** [comment]
This was fixed by #168. The latest master branch should work.

**Comment by keithbriggs** [comment]
Not sure about that - I am using the version I checked out yesterday.


________________________________

**Comment by ChristopherHogan** [comment]
The PR was merged last night around 7:45 pm CST. Did you try after that?

**Comment by keithbriggs** [comment]
What is CST?

________________________________

**Comment by ChristopherHogan** [comment]
Central standard time.

**Comment by keithbriggs** [comment]
Central to which country?


________________________________

**Comment by ChristopherHogan** [comment]
Sorry.  It would be UTC - 6.

**Comment by keithbriggs** [comment]
Thanks - I just cloned again and I am checking now...


K
________________________________

**Comment by stevengj** [comment]
Fixed?

**Comment by keithbriggs** [comment]
Yes, thank you.
